import { CallRecord, Lead, SystemMetrics } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Tariq Al-Mansoor',
    phone: '+971 50 492 8123',
    email: 'tariq.mansoor@gmail.com',
    area: 'Downtown Dubai',
    buildingName: 'Burj Crown',
    propertyType: 'Apartment',
    bedrooms: 2,
    estimatedSqft: 1180,
    askingPrice: 3450000,
    motivation: 'wants to sell and reinvest into off-plan Creek Harbour project',
    status: 'listing_agreed',
    campaignMode: 'secondary_listing_hunter',
    createdAt: '2026-09-14T09:30:00Z',
    lastCalledAt: '2026-09-15T11:20:00Z',
    callCount: 2,
    dossierSummary: 'PROSPECT DOSSIER [Tariq Al-Mansoor]\nBuilding: Burj Crown (Downtown)\nEst. Market Value: AED 3,450,000\nGolden Visa Qualified: YES\nStatus: Exclusive Listing Agreed at 2% RERA fee.',
    extractedStrategy: {
      suggestedPriceRange: 'AED 3,380,000 - AED 3,550,000',
      keyObjections: ['Asked standard RERA fee - agreed to 2% exclusive for 30 days.'],
      openingHook: 'Hi Tariq, Alexander from Aqarix. Reaching out about your Burj Crown 2-bed...',
      compsInsight: 'Downtown 2-bed avg sqft AED 2,850.',
    },
  },
  {
    id: 'lead-2',
    name: 'Sarah Jenkins',
    phone: '+44 7700 900412',
    email: 'sarah.j@techuk.io',
    area: 'Dubai Marina',
    buildingName: 'Marina Gate 1',
    propertyType: 'Apartment',
    bedrooms: 1,
    estimatedSqft: 760,
    askingPrice: 1750000,
    motivation: 'Relocating back to London end of month',
    status: 'meeting_booked',
    campaignMode: 'secondary_listing_hunter',
    createdAt: '2026-09-15T08:15:00Z',
    lastCalledAt: '2026-09-15T14:45:00Z',
    callCount: 1,
    dossierSummary: 'PROSPECT DOSSIER [Sarah Jenkins]\nBuilding: Marina Gate 1\nMotivation: High urgency (relocating end of month)\nStatus: In-person coffee meeting booked at DIFC office on Sunday 11 AM.',
    extractedStrategy: {
      suggestedPriceRange: 'AED 1,680,000 - AED 1,780,000',
      keyObjections: ['Wanted to deal with 1 direct cash buyer.'],
      openingHook: 'Hi Sarah, Alexander calling about your Marina Gate unit...',
      compsInsight: 'Marina Gate high floor commands AED 2,200/sqft.',
    },
  },
  {
    id: 'lead-3',
    name: 'Vikram Sharma',
    phone: '+971 55 981 4410',
    email: 'vikram.s@dubaiinvest.ae',
    area: 'Jumeirah Village Circle (JVC)',
    buildingName: 'Belgravia III',
    propertyType: 'Apartment',
    bedrooms: 1,
    estimatedSqft: 720,
    askingPrice: 920000,
    motivation: 'Capitalizing on 8.4% high yield market',
    status: 'ready_to_call',
    campaignMode: 'secondary_listing_hunter',
    createdAt: '2026-09-15T10:00:00Z',
    callCount: 0,
    dossierSummary: 'PROSPECT DOSSIER [Vikram Sharma]\nBuilding: Belgravia III (JVC)\nYield: 8.4% ROI\nStatus: Enriched, Ready for AI Cold Call.',
    extractedStrategy: {
      suggestedPriceRange: 'AED 890,000 - AED 945,000',
      keyObjections: ['May object to exclusive listing duration.'],
      openingHook: 'Hi Vikram, Alexander from Aqarix. Calling about your Belgravia unit...',
      compsInsight: 'JVC top performing yield area in 2026.',
    },
  },
  {
    id: 'lead-4',
    name: 'Elena Rostova',
    phone: '+971 52 331 9988',
    email: 'elena.r@luxurydubai.ru',
    area: 'Palm Jumeirah',
    buildingName: 'Royal Atlantis Residences',
    propertyType: 'Penthouse',
    bedrooms: 3,
    estimatedSqft: 2800,
    askingPrice: 14500000,
    motivation: 'Trophy asset portfolio optimization',
    status: 'ready_to_call',
    campaignMode: 'offplan_investor_closer',
    createdAt: '2026-09-15T12:00:00Z',
    callCount: 0,
    dossierSummary: 'PROSPECT DOSSIER [Elena Rostova]\nPalm Jumeirah Trophy Penthouse / Off-Plan Launch',
    extractedStrategy: {
      suggestedPriceRange: 'Starting AED 14,000,000',
      keyObjections: ['High net worth discretion requirement.'],
      openingHook: 'Good afternoon Elena, Alexander calling from Aqarix Luxury Division regarding Emaar Grand Resort pre-launch...',
      compsInsight: 'Palm Jumeirah penthouses avg AED 4,500/sqft.',
    },
  },
];

export const INITIAL_CALL_RECORDS: CallRecord[] = [
  {
    id: 'call-rec-101',
    leadId: 'lead-1',
    leadName: 'Tariq Al-Mansoor',
    leadPhone: '+971 50 492 8123',
    area: 'Downtown Dubai',
    campaignMode: 'secondary_listing_hunter',
    timestamp: '2026-09-15T11:20:00Z',
    durationSeconds: 245,
    outcome: 'listing_agreed',
    sentimentScore: 94,
    sellerMotivationScore: 9,
    recordingUrl: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
    transcript: [
      { speaker: 'agent', text: "Hi Tariq, this is Alexander calling from Aqarix Real Estate Dubai. Reaching out about your 2-bedroom unit in Burj Crown Downtown. We have two verified cash buyers looking in your stack right now, and I wanted to see if you'd consider a clean offer this week?", timestamp: '00:02' },
      { speaker: 'prospect', text: "Hello Alexander. Well, I was thinking about listing it next month actually, but I already have two agents who posted it on Property Finder.", timestamp: '00:14' },
      { speaker: 'agent', text: "I completely understand Tariq. But look, here is the honest truth in Downtown right now: having multiple agents post the exact same listing dilutes your property's value and makes buyers think you're desperate. We work on a 30-day exclusive off-market match at AED 3,450,000. If we don't bring a cash buyer at your target price, you owe zero.", timestamp: '00:32' },
      { speaker: 'prospect', text: "What is your commission rate?", timestamp: '00:50' },
      { speaker: 'agent', text: "Standard RERA 2%, but we earn our fee by negotiating the buyer UP, not discounting your net price down. Shall I send the 30-day agreement to your WhatsApp right now?", timestamp: '01:05' },
      { speaker: 'prospect', text: "Sounds fair Alexander. Send it over to my WhatsApp and let's get it done.", timestamp: '01:22' },
    ],
    keyTakeaways: [
      'Agreed to 30-day Exclusive Listing at AED 3,450,000',
      'Accepted 2% RERA standard commission',
      'Target price met; client wants cash buyer within 30 days',
    ],
    extractedData: {
      targetPriceAED: 3450000,
      desiredCommission: '2% Standard RERA',
      floorViewInfo: 'Burj Crown High Floor - Fountain View',
      urgentTimeline: true,
      whatsappSent: true,
      telegramAlertSent: true,
    },
  },
  {
    id: 'call-rec-102',
    leadId: 'lead-2',
    leadName: 'Sarah Jenkins',
    leadPhone: '+44 7700 900412',
    area: 'Dubai Marina',
    campaignMode: 'secondary_listing_hunter',
    timestamp: '2026-09-15T14:45:00Z',
    durationSeconds: 180,
    outcome: 'meeting_booked',
    sentimentScore: 88,
    sellerMotivationScore: 10,
    recordingUrl: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
    transcript: [
      { speaker: 'agent', text: "Hi Sarah, Alexander calling from Aqarix Dubai regarding your Marina Gate 1 unit. How are you today?", timestamp: '00:03' },
      { speaker: 'prospect', text: "Hi Alexander. I'm moving back to London at the end of the month so I need a quick resolution.", timestamp: '00:15' },
      { speaker: 'agent', text: "Makes total sense Sarah. Marina Gate 1-bedroom units are selling fast at AED 1,750,000. Let's sit down for 15 minutes at our DIFC office or over coffee near Marina Walk this Sunday at 11 AM to finalize buyer matching.", timestamp: '00:35' },
      { speaker: 'prospect', text: "Sunday at 11 AM works perfectly for me. Send me the calendar invite.", timestamp: '00:52' },
    ],
    keyTakeaways: [
      'Relocating to UK end of month (Urgency 10/10)',
      'In-person coffee meeting confirmed for Sunday 11:00 AM',
      'Target sales price AED 1,750,000',
    ],
    extractedData: {
      agreedMeetingTime: 'Sunday 20th Sept, 11:00 AM (DIFC / Marina Walk)',
      targetPriceAED: 1750000,
      urgentTimeline: true,
      whatsappSent: true,
      telegramAlertSent: true,
    },
  },
];

export const INITIAL_METRICS: SystemMetrics = {
  totalCallsMade: 52,
  listingsAgreed: 14,
  meetingsBooked: 18,
  eoisBooked: 8,
  avgCallDuration: 215, // seconds
  conversionRate: 68.4, // percentage
  activeCampaigns: 4,
};
